-- MySQL Script generated by MySQL Workbench
-- 09/10/18 15:50:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subcategoria` (
  `id_subcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome_subcategoria` VARCHAR(45) NOT NULL,
  `Categoria_id_categoria1` INT NOT NULL,
  PRIMARY KEY (`id_subcategoria`),
  INDEX `fk_subcategoria_Categoria1_idx` (`Categoria_id_categoria1` ASC),
  CONSTRAINT `fk_subcategoria_Categoria1`
    FOREIGN KEY (`Categoria_id_categoria1`)
    REFERENCES `mydb`.`Categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(45) NOT NULL,
  `saldo_produto` INT NULL,
  `codbarras_produto` VARCHAR(15) NOT NULL,
  `valor_produto` FLOAT NOT NULL,
  `subcategoria_id_subcategoria` INT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_produto_subcategoria1_idx` (`subcategoria_id_subcategoria` ASC),
  CONSTRAINT `fk_produto_subcategoria1`
    FOREIGN KEY (`subcategoria_id_subcategoria`)
    REFERENCES `mydb`.`subcategoria` (`id_subcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `id_pagamento` INT NOT NULL AUTO_INCREMENT,
  `nome_pagamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `data_venda` DATETIME NULL,
  `Pagamento_id_pagamento` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_venda_Pagamento1_idx` (`Pagamento_id_pagamento` ASC),
  CONSTRAINT `fk_venda_Pagamento1`
    FOREIGN KEY (`Pagamento_id_pagamento`)
    REFERENCES `mydb`.`Pagamento` (`id_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda_has_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda_has_produto` (
  `venda_id_venda` INT NOT NULL,
  `produto_id_produto` INT NOT NULL,
  `quantidade_itens` INT NULL,
  PRIMARY KEY (`venda_id_venda`, `produto_id_produto`),
  INDEX `fk_venda_has_produto_produto1_idx` (`produto_id_produto` ASC),
  INDEX `fk_venda_has_produto_venda1_idx` (`venda_id_venda` ASC),
  CONSTRAINT `fk_venda_has_produto_venda1`
    FOREIGN KEY (`venda_id_venda`)
    REFERENCES `mydb`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_has_produto_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `mydb`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
