-- MySQL Script generated by MySQL Workbench
-- 10/29/18 16:57:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id_categoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subcategoria` (
  `id_subcategoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_subcategoria` VARCHAR(45) NOT NULL,
  `categoria_id_categoria` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_subcategoria`),
  INDEX `fk_subcategoria_categoria1_idx` (`categoria_id_categoria` ASC),
  CONSTRAINT `fk_subcategoria_categoria1`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `mydb`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `id_produto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(45) NOT NULL,
  `saldo_produto` INT NOT NULL,
  `codbarras_produto` BIGINT(14) ZEROFILL UNSIGNED NOT NULL,
  `valor_produto` DECIMAL(5,2) UNSIGNED NOT NULL,
  `subcategoria_id_subcategoria` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_produto_subcategoria1_idx` (`subcategoria_id_subcategoria` ASC),
  CONSTRAINT `fk_produto_subcategoria1`
    FOREIGN KEY (`subcategoria_id_subcategoria`)
    REFERENCES `mydb`.`subcategoria` (`id_subcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `id_pagamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_pagamento` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_pagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `id_venda` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_venda` DATETIME NOT NULL,
  `pagamento_id_pagamento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_venda_pagamento1_idx` (`pagamento_id_pagamento` ASC),
  CONSTRAINT `fk_venda_pagamento1`
    FOREIGN KEY (`pagamento_id_pagamento`)
    REFERENCES `mydb`.`pagamento` (`id_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda_has_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda_has_produto` (
  `venda_id_venda` INT UNSIGNED NOT NULL,
  `produto_id_produto` INT UNSIGNED NOT NULL,
  `quantidade_produto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`venda_id_venda`, `produto_id_produto`),
  INDEX `fk_venda_has_produto_produto1_idx` (`produto_id_produto` ASC),
  INDEX `fk_venda_has_produto_venda1_idx` (`venda_id_venda` ASC),
  CONSTRAINT `fk_venda_has_produto_venda1`
    FOREIGN KEY (`venda_id_venda`)
    REFERENCES `mydb`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_has_produto_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `mydb`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
